### PR TITLE
Windows build support

### PR DESCRIPTION
**Pull request by krystophv**
I can't take credit (or claim much knowledge about) the bulk of this. I just took a fork of a fork and applied a patch from another project using `talib` to fix the Windows build. I've tested it on Win x64 and Linux.

### CODE REVIEW

**Comment by krystophv** [comment]
Can potentially remedy #8 and #53

**Comment by oransel** [comment]
I'll look into this shortly. Thank you for all  your hard work.

**Comment by oransel** [comment]
Can you provide instructions for Windows dev system setup? I installed Visual Studio 2015 MSBuild Tools. It is failing to compile. We should also consider pre-built libraries to download for both x86 and x64 platforms.

**Comment by krystophv** [comment]
I believe I've always used `npm install --global --production windows-build-tools` - try that and let me know if it still doesn't work.

Do you mean having the `talib` libraries pre-compiled or having `node-talib` native modules pre-compiled? I don't have much experience publishing pre-compiled native modules, so I'm not sure what would be required for that.

**Comment by oransel** [comment]
Sounds good. With the `windows-build-tools` module, the dev environment was set up correctly and the module compiled, with warnings. Unfortunately, there is a small issue with building on Win x86. The reference path at https://github.com/krystophv/node-talib/blob/master/src/lib/build.js#L6 is correct when installed on Win x64. I'll merge for now and this needs to be fixed before public release.

**Comment by oransel** [comment]
@krystophv this project has done a good job precompiling the native module [drivelist](https://github.com/resin-io-modules/drivelist).

**Comment by danielsokolowski** [comment]
+1 to @krystophv - this idea of building everything from source is just wasted effort, more often than not something just breaks.

**Pull request merged**
