### PR TITLE
supporting synchronized call and fix running in child thread

### PR DESCRIPTION
**Pull request by z-hao-wang**
see readme examples

### CODE REVIEW

**Comment by z-hao-wang** [comment]
this also fixes context issue when running in child processes.
https://github.com/nodejs/node/issues/21481

**Comment by danielsokolowski** [comment]
This looks good to me, can it be merged in?

**Comment by z-hao-wang** [comment]
@danielsokolowski  the example are in the readme, you can avoid using a callback.
The original purpose is that I  have to work with a different lib that doesn't support callback type calls.
Also this enables to run in forked child thread.

**Comment by oransel** [comment]
May be the sync functions need to be separate than the async functions so we don't loose the async functionality

**Comment by z-hao-wang** [comment]
@oransel I believe this change is fully backward compatible, it will use async method if you pass in a callback, otherwise it will do sync call. how else could we separate the sync methods?

**Comment by oransel** [comment]
@z-hao-wang Sounds good. If you can resolve the merge conflicts, i can pull in and test.

**Comment by z-hao-wang** [comment]
@oransel Just merged conflicts and test on my side worked.

**Pull request merged**
