### PR TITLE
potentially fix windows x86 build

### PR DESCRIPTION
**Pull request by krystophv**
I believe this will fix the x86/x64 path issue on Windows, but I don't have an x86 machine to test against. Since you were able to detect that there was an issue with the build on an x86 machine, I'm guessing that perhaps you have one to test against? 

Thanks for being so responsive with the other PR.

### CODE REVIEW

**Comment by oransel** [comment]
Thank you for submitting the patch. MSBuild reference is correct now. 

However, there are new issues for x86. The .NET Framework 4.0 reference is not correct. If you copy what ever 4.x framework version in `C:\Program Files\Reference Assemblies\Microsoft\Framework\.NETFramework\` to 4.0, it passes the compilation process but linker reports unresolved external symbols for the TA functions, of which may be caused by the `MSB8012` warnings given during specific library compilation processes.

**Comment by krystophv** [comment]
Ok, I think I had to just pass the correct platform to the MSBuild command. Sorry to have you keep trying to no avail, but perhaps this change fixes it?

**Comment by oransel** [comment]
Here is the [output.txt](https://github.com/oransel/node-talib/files/1617125/output.txt)

**Comment by krystophv** [comment]
Thanks @oransel - it looks like you (and most users) will have a more up to date version of the .NETFramework available. The code will now attempt to locate the latest version and use it for the build instead of the original v4.0

**Comment by oransel** [comment]
@krystophv thank you very much for all your help. I pushed minor fixes for x86 to the master. Can you test on x64?

**Comment by krystophv** [comment]
LGTM! Compiles with no errors on my x64 system.

**Pull request merged**
